version: '3'

services:

  postgres:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass

  pgweb:
    image: donnex/pgweb
    links:
      - postgres
    ports:
      - 8080:8080